"""Initial migration.

Revision ID: be6f4a28e6cc
Revises: 
Create Date: 2021-09-03 17:36:36.192171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6f4a28e6cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radio_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('streamUrl', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radio_stations')
    # ### end Alembic commands ###
